# Hope this works
name: Create .upmconfig.toml UPM authentication file
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .upmconfig.toml UPM authentication file
        run: |
          mkdir /home/runner/work/_temp/_github_home
          cd /home/runner/work/_temp/_github_home
          echo "[npmAuth.\"https://upm.example.com\"]" >> .upmconfig.toml
          echo "alwaysAuth = true" >> .upmconfig.toml
          echo "token = \"${{ secrets.NPM_TOKEN }}\"" >> .upmconfig.toml